using System.Text.Json;

namespace TokenGuard.Tools.Tools;

/// <summary>
/// Reads the content of a text file from a test-owned workspace.
/// </summary>
/// <remarks>
/// The tool resolves paths relative to the provided workspace directory and rejects traversal so E2E runs stay
/// hermetic while still exercising a realistic file-reading tool.
/// </remarks>
public sealed class ReadFileTool(string workspaceDirectory) : ITool
{
    /// <summary>
    /// Gets the tool name.
    /// </summary>
    public string Name => "read_file";

    /// <summary>
    /// Gets the tool description.
    /// </summary>
    public string Description => "Reads the content of a specified text file from the task workspace.";

    /// <summary>
    /// Gets the tool schema.
    /// </summary>
    public JsonDocument? ParametersSchema => JsonDocument.Parse("""
        {
            "type": "object",
            "properties": {
                "filename": { "type": "string", "description": "The name of the file to read from the task workspace." }
            },
            "required": ["filename"],
            "additionalProperties": false
        }
        """);

    /// <summary>
    /// Reads the requested file content.
    /// </summary>
    /// <param name="argumentsJson">The JSON arguments generated by the model.</param>
    /// <returns>The file contents, or an error message when the file is missing or invalid.</returns>
    public string Execute(string argumentsJson)
    {
        try
        {
            using var doc = JsonDocument.Parse(argumentsJson);
            if (!doc.RootElement.TryGetProperty("filename", out var filenameProperty))
            {
                return "Error: Missing 'filename' argument.";
            }

            var filename = filenameProperty.GetString();
            if (string.IsNullOrWhiteSpace(filename))
            {
                return "Error: 'filename' cannot be empty.";
            }

            var path = WorkspacePathResolver.Resolve(workspaceDirectory, filename);
            if (!File.Exists(path))
            {
                return $"File not found: {filename}";
            }

            return File.ReadAllText(path);
        }
        catch (Exception ex)
        {
            return $"Error reading file: {ex.Message}";
        }
    }
}
