using System.Text.Json;
using TokenGuard.Core.Models.Content;

namespace TokenGuard.Samples.Console.Tools;

/// <summary>
/// Defines a callable tool that an LLM can discover, invoke, and round-trip through conversation history.
/// </summary>
/// <remarks>
/// <para>
/// Implement <see cref="ITool"/> for operations that should be exposed to a model as structured function calls. The
/// metadata members describe the tool to the provider, while <see cref="Execute(string)"/> performs the actual work
/// once the model selects the tool.
/// </para>
/// <para>
/// TokenGuard records tool calls through <see cref="ToolUseContent"/> and tool outputs through
/// <see cref="ToolResultContent"/>, so the contract intentionally keeps execution synchronous and serialization-focused.
/// Adapters or hosting layers can wrap this interface with their own async or dependency-injection policies.
/// </para>
/// </remarks>
public interface ITool
{
    /// <summary>
    /// Gets the stable tool name exposed to the model.
    /// </summary>
    /// <remarks>
    /// This value is used as the function identifier in provider payloads and should remain stable over time so model
    /// prompts, tool-call traces, and recorded histories continue to line up.
    /// </remarks>
    string Name { get; }

    /// <summary>
    /// Gets the natural-language description that helps the model decide when to invoke the tool.
    /// </summary>
    /// <remarks>
    /// Keep this description task-oriented and behavior-focused. Providers typically surface it directly to the model as
    /// part of tool selection guidance.
    /// </remarks>
    string Description { get; }

    /// <summary>
    /// Gets the JSON Schema that describes the tool's accepted arguments.
    /// </summary>
    /// <remarks>
    /// Return <see langword="null"/> when the tool takes no structured arguments. When a schema is supplied, it should
    /// match the JSON shape expected by <see cref="Execute(string)"/> so provider-generated calls can be validated and
    /// deserialized reliably.
    /// </remarks>
    JsonDocument? ParametersSchema { get; }

    /// <summary>
    /// Executes the tool against a provider-supplied JSON argument payload.
    /// </summary>
    /// <remarks>
    /// Implementations should treat <paramref name="argumentsJson"/> as the exact payload emitted by the model for the
    /// schema advertised by <see cref="ParametersSchema"/>. The returned string is typically recorded into
    /// <see cref="ToolResultContent"/> and may therefore be replayed to the model in later turns.
    /// </remarks>
    /// <param name="argumentsJson">The raw JSON argument object generated by the model.</param>
    /// <returns>The textual tool result to record and send back into the conversation loop.</returns>
    string Execute(string argumentsJson);
}
