using System.Text.Json;

namespace TokenGuard.TestCommon.Tools;

/// <summary>
/// Creates a text file within a test-owned workspace.
/// </summary>
/// <remarks>
/// The tool mirrors the sample application's file-creation flow while constraining writes to the temporary E2E
/// workspace so tests remain isolated and repeatable.
/// </remarks>
public sealed class CreateTextFileTool(string workspaceDirectory) : ITool
{
    /// <summary>
    /// Gets the tool name.
    /// </summary>
    public string Name => "create_text_file";

    /// <summary>
    /// Gets the tool description.
    /// </summary>
    public string Description => "Creates a text file with optional initial content in the task workspace.";

    /// <summary>
    /// Gets the tool schema.
    /// </summary>
    public JsonDocument? ParametersSchema => JsonDocument.Parse("""
        {
            "type": "object",
            "properties": {
                "filename": { "type": "string", "description": "The name of the file to create in the task workspace." },
                "content": { "type": "string", "description": "Optional initial content for the file." }
            },
            "required": ["filename"],
            "additionalProperties": false
        }
        """);

    /// <summary>
    /// Creates the requested file.
    /// </summary>
    /// <param name="argumentsJson">The JSON arguments generated by the model.</param>
    /// <returns>A status message describing the created file or any validation failure.</returns>
    public string Execute(string argumentsJson)
    {
        try
        {
            using var doc = JsonDocument.Parse(argumentsJson);
            if (!doc.RootElement.TryGetProperty("filename", out var filenameProperty))
            {
                return "Error: Missing 'filename' argument.";
            }

            var filename = filenameProperty.GetString();
            if (string.IsNullOrWhiteSpace(filename))
            {
                return "Error: 'filename' cannot be empty.";
            }

            var path = WorkspacePathResolver.Resolve(workspaceDirectory, filename);
            var directory = Path.GetDirectoryName(path);
            if (!string.IsNullOrWhiteSpace(directory))
            {
                Directory.CreateDirectory(directory);
            }

            var content = doc.RootElement.TryGetProperty("content", out var contentProperty)
                ? contentProperty.GetString() ?? string.Empty
                : string.Empty;

            File.WriteAllText(path, content);
            return $"Created file: {Path.GetFileName(path)}";
        }
        catch (Exception ex)
        {
            return $"Error creating file: {ex.Message}";
        }
    }
}
