using System.Text.Json;

namespace TokenGuard.TestCommon.Tools;

/// <summary>
/// Replaces the content of an existing text file within a test-owned workspace.
/// </summary>
/// <remarks>
/// This keeps write operations scoped to a temporary directory so the model can perform an actual edit cycle during
/// E2E execution without mutating repository sources.
/// </remarks>
public sealed class EditTextFileTool(string workspaceDirectory) : ITool
{
    /// <summary>
    /// Gets the tool name.
    /// </summary>
    public string Name => "edit_text_file";

    /// <summary>
    /// Gets the tool description.
    /// </summary>
    public string Description => "Replaces the content of an existing text file in the task workspace.";

    /// <summary>
    /// Gets the tool schema.
    /// </summary>
    public JsonDocument? ParametersSchema => JsonDocument.Parse("""
        {
            "type": "object",
            "properties": {
                "filename": { "type": "string", "description": "The name of the file to edit in the task workspace." },
                "content": { "type": "string", "description": "The full replacement content to write." }
            },
            "required": ["filename", "content"],
            "additionalProperties": false
        }
        """);

    /// <summary>
    /// Replaces the requested file content.
    /// </summary>
    /// <param name="argumentsJson">The JSON arguments generated by the model.</param>
    /// <returns>A status message describing the update or the validation failure.</returns>
    public string Execute(string argumentsJson)
    {
        try
        {
            using var doc = JsonDocument.Parse(argumentsJson);
            if (!doc.RootElement.TryGetProperty("filename", out var filenameProperty))
            {
                return "Error: Missing 'filename' argument.";
            }

            if (!doc.RootElement.TryGetProperty("content", out var contentProperty))
            {
                return "Error: Missing 'content' argument.";
            }

            var filename = filenameProperty.GetString();
            if (string.IsNullOrWhiteSpace(filename))
            {
                return "Error: 'filename' cannot be empty.";
            }

            var path = WorkspacePathResolver.Resolve(workspaceDirectory, filename);
            if (!File.Exists(path))
            {
                return $"File not found: {filename}";
            }

            File.WriteAllText(path, contentProperty.GetString() ?? string.Empty);
            return $"Updated file: {Path.GetFileName(path)}";
        }
        catch (Exception ex)
        {
            return $"Error editing file: {ex.Message}";
        }
    }
}
