namespace SemanticFold.Core.Models.Content;

/// <summary>
/// Represents a model-emitted request to invoke a named tool with structured arguments.
/// </summary>
/// <remarks>
/// <see cref="ToolUseContent"/> preserves provider tool-call intent in a transport-neutral form so calling code can
/// execute the requested tool and later correlate the response using the same <see cref="ToolCallId"/>.
/// </remarks>
public sealed record ToolUseContent : ContentSegment
{
    /// <summary>
    /// Initializes a new <see cref="ToolUseContent"/> instance.
    /// </summary>
    /// <remarks>
    /// The constructor validates all fields because tool-call replay and tool-result matching depend on these values
    /// remaining complete and stable across the full agent loop.
    /// </remarks>
    /// <param name="ToolCallId">The provider-stable identifier used to correlate this call with its eventual result.</param>
    /// <param name="ToolName">The name of the tool the model chose to invoke.</param>
    /// <param name="ArgumentsJson">The raw JSON argument payload generated by the model.</param>
    /// <exception cref="ArgumentException">Thrown when any argument is null or whitespace.</exception>
    public ToolUseContent(string ToolCallId, string ToolName, string ArgumentsJson)
    {
        if (string.IsNullOrWhiteSpace(ToolCallId))
        {
            throw new ArgumentException("Tool call id cannot be null or whitespace.", nameof(ToolCallId));
        }

        if (string.IsNullOrWhiteSpace(ToolName))
        {
            throw new ArgumentException("Tool name cannot be null or whitespace.", nameof(ToolName));
        }

        if (string.IsNullOrWhiteSpace(ArgumentsJson))
        {
            throw new ArgumentException("Arguments JSON cannot be null or whitespace.", nameof(ArgumentsJson));
        }

        this.ToolCallId = ToolCallId;
        this.ToolName = ToolName;
        this.ArgumentsJson = ArgumentsJson;
    }

    /// <summary>
    /// Gets the identifier used to correlate this tool call with a later <see cref="ToolResultContent"/>.
    /// </summary>
    public string ToolCallId { get; init; }

    /// <summary>
    /// Gets the name of the tool the model requested.
    /// </summary>
    public string ToolName { get; init; }

    /// <summary>
    /// Gets the raw JSON argument payload for the requested tool invocation.
    /// </summary>
    public string ArgumentsJson { get; init; }
}
