<Project>
  <PropertyGroup>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DeterministicSourcePaths Condition="'$(GITHUB_ACTIONS)' == 'true'">true</DeterministicSourcePaths>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup Condition="Exists('$(MSBuildProjectDirectory)/PackageReadme.md')">
    <PackageReadmeFile>PackageReadme.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup Condition="Exists('$(MSBuildProjectDirectory)/PackageReadme.md')">
    <None Include="PackageReadme.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
